import {MONTHLY,money,dateKey,initial,validate,balance,summary,milestones,buckets} from './core.js';
const $=id=>document.getElementById(id);let state=initial(),db,period='day',pendingInstall,toastTimer;const channel='BroadcastChannel'in window?new BroadcastChannel('tabungan-updates'):null;
function toast(message){$('toast').textContent=message;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),4500)}
function openDB(){return new Promise((resolve,reject)=>{let r=indexedDB.open('tabungan-pribadi',1);r.onupgradeneeded=()=>r.result.createObjectStore('data');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);r.onblocked=()=>reject(Error('Tutup tab lama lalu buka kembali aplikasi.'))})}
async function read(){return new Promise((resolve,reject)=>{let t=db.transaction('data'),r=t.objectStore('data').get('state');r.onsuccess=()=>{try{resolve(r.result?validate(r.result):initial())}catch(e){reject(e)}};r.onerror=()=>reject(r.error)})}
function save(transform){return new Promise((resolve,reject)=>{if(!db)return reject(Error('Penyimpanan tidak tersedia. Aktifkan penyimpanan browser.'));let tx=db.transaction('data','readwrite'),store=tx.objectStore('data'),r=store.get('state'),next,reason;r.onsuccess=()=>{try{next=validate(transform(r.result?validate(r.result):initial()));store.put(next,'state')}catch(e){reason=e;tx.abort()}};tx.oncomplete=()=>{state=next;render();channel?.postMessage('updated');resolve()};tx.onabort=()=>reject(reason||Error('Data gagal disimpan. Ruang penyimpanan mungkin penuh.'));tx.onerror=()=>{reason=Error('Data gagal disimpan. Coba export backup dan periksa penyimpanan.')}})}
function render(){const v=summary(state);$('balance').textContent=money(v.total);$('target').textContent=money(state.target);$('remaining').textContent=money(v.left);$('progress-label').textContent=`${v.percent.toLocaleString('id-ID',{maximumFractionDigits:1})}% dari target`;$('progress-fill').style.width=v.percent+'%';$('progress').setAttribute('aria-valuenow',v.percent);$('encouragement').textContent=v.total===0?'Perjalanan besar dimulai dari tabungan pertama.':v.left===0?'Kamu berhasil. Ini hasil kerja kerasmu sendiri! 🎉':'Pelan-pelan, impianmu semakin dekat.';
 $('countdown').replaceChildren(document.createTextNode(v.days===null?'—':v.days.toLocaleString('id-ID')));let unit=document.createElement('span');unit.textContent='hari lagi';$('countdown').append(unit);const eta=new Date();if(v.days!==null&&v.days<365000){eta.setDate(eta.getDate()+v.days);$('estimate-date').textContent=v.days===0?'Target tercapai!':eta.toLocaleDateString('id-ID',{day:'numeric',month:'long',year:'numeric'})}else $('estimate-date').textContent=v.days===null?'Mulai langkah pertamamu':'Masih perjalanan panjang';$('estimate-note').textContent=v.rate>0?`Rata-rata ${money(Math.round(v.rate))}/hari sejak transaksi pertama, termasuk penarikan. Estimasi berubah mengikuti ritmemu.`:'Estimasi muncul setelah saldo bersih positif. Dihitung sejak transaksi pertama sampai hari ini.';
 $('month-name').textContent=new Date().toLocaleDateString('id-ID',{month:'long',year:'numeric'});$('month-total').textContent=money(v.month);$('month-fill').style.width=Math.max(0,Math.min(100,v.month/MONTHLY*100))+'%';let remain=Math.max(0,MONTHLY-v.month);$('month-remaining').textContent=remain?money(remain)+' lagi':'Target bulan ini tercapai ✓';let now=new Date(),days=new Date(now.getFullYear(),now.getMonth()+1,0).getDate()-now.getDate()+1;$('daily-tip').textContent=remain?`${money(Math.ceil(remain/days))}/hari untuk ${days} hari tersisa`:'Pertahankan ritmemu. Kamu luar biasa.';
 $('milestones').replaceChildren();const all=milestones(state.target);let visible=all.length>8?[...all.filter(n=>n<=v.total).slice(-2),...all.filter(n=>n>v.total).slice(0,4)]:all;if(!visible.includes(state.target))visible.push(state.target);for(const n of visible){let row=document.createElement('div');row.className='milestone'+(v.total>=n?' done':'');let icon=document.createElement('span');icon.className='milestone-icon';icon.textContent=v.total>=n?'✓':n===state.target?'✦':'○';let title=document.createElement('strong');title.textContent=money(n);let status=document.createElement('small');status.textContent=v.total>=n?'Tercapai':n===state.target?'Tujuan akhir':'Milestone';row.append(icon,title,status);$('milestones').append(row)}renderChart();renderHistory();$('backup-date').textContent=state.lastBackup?'Export terakhir: '+new Date(state.lastBackup).toLocaleString('id-ID'):'Belum pernah export backup.';}
function renderChart(){const rows=buckets(state,period);const max=Math.max(1,...rows.flatMap(r=>[r.incoming,r.outgoing]));$('chart').replaceChildren();for(const r of rows){let col=document.createElement('div');col.className='chart-col';col.title=`${r.from} – ${r.to}: masuk ${money(r.incoming)}, keluar ${money(r.outgoing)}`;col.setAttribute('aria-label',col.title);col.tabIndex=0;let bars=document.createElement('div');bars.className='bars';for(const [n,c] of [[r.incoming,'bar'],[r.outgoing,'bar out']]){let b=document.createElement('div');b.className=c;b.style.height=n/max*110+'px';bars.append(b)}let label=document.createElement('small');label.textContent=r.label;col.append(bars,label);$('chart').append(col)}let incoming=rows.reduce((n,r)=>n+r.incoming,0),outgoing=rows.reduce((n,r)=>n+r.outgoing,0);$('stat-in').textContent=money(incoming);$('stat-out').textContent=money(outgoing);$('stat-net').textContent=money(incoming-outgoing);$('chart-caption').textContent=`${period==='day'?'7 hari':period==='week'?'7 minggu (mulai Senin)':'6 bulan'} terakhir · Biru: masuk · Abu-abu: keluar${incoming+outgoing===0?' · Belum ada transaksi':''}`;}
function renderHistory(){const filter=$('history-filter').value;const transactions=[...state.transactions].reverse().sort((a,b)=>b.date.localeCompare(a.date)).filter(t=>filter==='all'||t.type===filter);$('history-count').textContent=`${state.transactions.length} transaksi · Semua langkahmu berarti.`;$('history').replaceChildren();if(!transactions.length){let e=document.createElement('div');e.className='empty';let b=document.createElement('b');b.textContent=state.transactions.length?'Tidak ada transaksi pada filter ini.':'Hal besar dimulai dari Rp0.';e.append(b,document.createTextNode('Catat langkahmu lewat tombol Tambah tabungan.'));$('history').append(e)}for(const t of transactions){let row=document.createElement('div');row.className='transaction '+t.type;let icon=document.createElement('div');icon.className='soft-icon';icon.textContent=t.type==='in'?'↙':'↗';let info=document.createElement('div');info.className='transaction-info';let title=document.createElement('strong');title.textContent=t.note||(t.type==='in'?'Tambah tabungan':'Penarikan tabungan');let date=document.createElement('small');date.textContent=new Date(t.date+'T12:00:00').toLocaleDateString('id-ID',{day:'numeric',month:'long',year:'numeric'});info.append(title,date);let val=document.createElement('strong');val.className='transaction-value';val.textContent=(t.type==='in'?'+':'−')+money(t.amount);let del=document.createElement('button');del.className='delete';del.textContent='×';del.setAttribute('aria-label','Hapus transaksi '+title.textContent);del.onclick=()=>confirmAction('Hapus transaksi?',`${title.textContent} · ${money(t.amount)}. Saldo akan dihitung ulang.`,async()=>{await save(s=>({...s,transactions:s.transactions.filter(x=>x.id!==t.id)}));toast('Transaksi dihapus.')});row.append(icon,info,val,del);$('history').append(row)}}
function confirmAction(title,text,action){$('confirm-title').textContent=title;$('confirm-text').textContent=text;$('confirm-dialog').showModal();$('confirm-ok').onclick=async()=>{const b=$('confirm-ok');b.disabled=true;try{await action();$('confirm-dialog').close()}catch(e){$('confirm-text').textContent=e.message}finally{b.disabled=false}}}
$('confirm-cancel').onclick=()=>$('confirm-dialog').close();document.querySelectorAll('.close').forEach(b=>b.onclick=()=>b.closest('dialog').close());
function transaction(type){$('transaction-form').reset();$('transaction-type').value=type;$('transaction-title').textContent=type==='in'?'Tambah tabungan':'Kurangi tabungan';$('date').value=dateKey();$('date').max=dateKey();$('date').min='2000-01-01';$('transaction-error').textContent='';$('transaction-dialog').showModal();$('amount').focus()}
$('deposit').onclick=()=>transaction('in');$('withdraw').onclick=()=>transaction('out');function parseAmount(v){if(!/^[\d.\s]+$/.test(v))return NaN;return Number(v.replace(/[.\s]/g,''))}for(const id of ['amount','target-input'])$(id).addEventListener('input',()=>{let v=$(id).value.replace(/[^\d]/g,'');$(id).value=v?Number(v).toLocaleString('id-ID'):''});document.querySelectorAll('[data-amount]').forEach(b=>b.onclick=()=>{$('amount').value=Number(b.dataset.amount).toLocaleString('id-ID')});
$('transaction-form').onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{const t={id:crypto.randomUUID(),type:$('transaction-type').value,amount:parseAmount($('amount').value),date:$('date').value,note:$('note').value.trim()};let reached=[];await save(s=>{const previous=balance(s);s.transactions.push(t);const total=balance(s);reached=milestones(s.target).filter(n=>n>previous&&n<=total&&!s.celebrated.includes(n));s.celebrated.push(...reached);return s});$('transaction-dialog').close();if(reached.length)celebrate(Math.max(...reached));else toast('Transaksi tersimpan.');navigator.storage?.persist?.().catch(()=>{})}catch(e){$('transaction-error').textContent=e.message}finally{b.disabled=false}};
function celebrate(n){toast(`🎉 ${money(n)} tercapai. Hasil usahamu sendiri!`);if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;for(let i=0;i<45;i++){let p=document.createElement('i');p.className='confetti';p.style.left=Math.random()*100+'%';p.style.background=['#0071e3','#71b9fa','#ffcd65','#9ce2c4'][i%4];p.style.animationDelay=Math.random()*.6+'s';$('confetti').append(p)}setTimeout(()=>$('confetti').replaceChildren(),3400)}
function settings(){$('target-input').value=state.target.toLocaleString('id-ID');$('settings-error').textContent='';$('settings-dialog').showModal()}$('settings').onclick=settings;$('edit-target').onclick=settings;$('backup-footer').onclick=settings;
$('target-form').onsubmit=async e=>{e.preventDefault();try{await save(s=>({...s,target:parseAmount($('target-input').value)}));toast('Target diperbarui.')}catch(e){$('settings-error').textContent=e.message}};
$('export').onclick=async()=>{try{const fresh=await read();const exported={...fresh,lastBackup:new Date().toISOString()};let url=URL.createObjectURL(new Blob([JSON.stringify(exported,null,2)],{type:'application/json'}));let a=document.createElement('a');a.href=url;a.download=`tabungan-backup-${dateKey()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);await save(s=>({...s,lastBackup:exported.lastBackup}));toast('Backup diexport. Simpan file di tempat aman.')}catch(e){$('settings-error').textContent=e.message}};
$('import').onclick=()=>$('import-file').click();$('import-file').onchange=async()=>{try{const f=$('import-file').files[0];if(!f)return;if(f.size>20000000)throw Error('File terlalu besar (maksimal 20 MB).');const imported=validate(JSON.parse(await f.text()));confirmAction('Ganti data dengan backup?',`Backup berisi ${imported.transactions.length} transaksi, saldo ${money(balance(imported))}, target ${money(imported.target)}. Seluruh data saat ini akan diganti. Export data saat ini terlebih dahulu jika diperlukan.`,async()=>{await save(()=>imported);toast('Backup berhasil dipulihkan.')})}catch(e){$('settings-error').textContent=e instanceof SyntaxError?'File bukan JSON yang valid.':e.message}finally{$('import-file').value=''}};
document.querySelectorAll('[data-period]').forEach(b=>b.onclick=()=>{period=b.dataset.period;document.querySelectorAll('[data-period]').forEach(x=>x.classList.toggle('active',x===b));renderChart()});$('history-filter').onchange=renderHistory;
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();pendingInstall=e});$('install').onclick=async()=>{if(pendingInstall){await pendingInstall.prompt();pendingInstall=null}else settings()};window.addEventListener('appinstalled',()=>{$('install').hidden=true;toast('Aplikasi terpasang.')});function connection(){$('connection').textContent=navigator.onLine?'Pribadi · di perangkat ini':'Offline · tetap bisa mencatat'}window.addEventListener('online',connection);window.addEventListener('offline',connection);connection();
try{db=await openDB();state=await read();db.onversionchange=()=>db.close();render();$('storage-status').textContent='✓ Tersimpan di perangkat ini'}catch(e){$('storage-status').textContent='Penyimpanan bermasalah';toast('Data tidak dapat dibuka: '+e.message);$('deposit').disabled=true;$('withdraw').disabled=true}
channel&&(channel.onmessage=async()=>{try{state=await read();render()}catch(e){toast(e.message)}});document.addEventListener('visibilitychange',async()=>{if(!document.hidden&&db){try{state=await read();render()}catch(e){toast(e.message)}}});setInterval(()=>{if(db)render()},60000);
if('serviceWorker'in navigator){try{await navigator.serviceWorker.register('./sw.js');await navigator.serviceWorker.ready;$('offline-status').textContent='✓ Mode offline siap. Aplikasi dapat dibuka tanpa internet.'}catch{$('offline-status').textContent='Mode offline belum siap. Gunakan HTTPS atau localhost, lalu buka ulang saat online.'}}else $('offline-status').textContent='Browser ini belum mendukung mode offline.';
