export const MONTHLY=10000000;
export const money=n=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(n).replace(/\s/g,'');
export const dateKey=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
export const dayNumber=s=>Date.parse(s+'T00:00:00Z')/86400000;
export const initial=()=>({version:1,target:30000000,transactions:[],celebrated:[],lastBackup:null});
export const balance=s=>s.transactions.reduce((v,t)=>v+(t.type==='in'?t.amount:-t.amount),0);
export function validate(s,today=dateKey()){
 if(!s||s.version!==1||!Number.isSafeInteger(s.target)||s.target<=0||s.target>1000000000000||!Array.isArray(s.transactions)||s.transactions.length>100000)throw Error('Format backup atau target tidak valid.');
 const ids=new Set();for(const t of s.transactions){if(!t||typeof t.id!=='string'||!t.id||t.id.length>100||ids.has(t.id)||!['in','out'].includes(t.type)||!Number.isSafeInteger(t.amount)||t.amount<=0||t.amount>1000000000000||typeof t.note!=='string'||t.note.length>200||typeof t.date!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(t.date)||!Number.isFinite(dayNumber(t.date))||new Date(t.date+'T00:00:00Z').toISOString().slice(0,10)!==t.date||t.date<'2000-01-01'||t.date>today)throw Error('Ada transaksi tidak valid, tanggal mendatang, atau ID ganda.');ids.add(t.id)}
 const byDate=new Map();for(const t of s.transactions)byDate.set(t.date,(byDate.get(t.date)||0)+(t.type==='in'?t.amount:-t.amount));let running=0;for(const [,n]of [...byDate].sort(([a],[b])=>a.localeCompare(b))){running+=n;if(running<0||!Number.isSafeInteger(running))throw Error('Transaksi menyebabkan saldo negatif pada suatu tanggal. Periksa tanggal dan nominal.');}
 return {version:1,target:s.target,transactions:s.transactions.map(({id,type,amount,date,note})=>({id,type,amount,date,note})),celebrated:Array.isArray(s.celebrated)?s.celebrated.filter(n=>Number.isSafeInteger(n)&&n>0).slice(0,10000):[],lastBackup:typeof s.lastBackup==='string'?s.lastBackup:null};
}
export function summary(s,today=dateKey()) {const total=balance(s),left=Math.max(0,s.target-total),month=s.transactions.filter(t=>t.date.startsWith(today.slice(0,7))).reduce((v,t)=>v+(t.type==='in'?t.amount:-t.amount),0);const first=s.transactions.map(t=>t.date).sort()[0];const elapsed=first?Math.max(1,dayNumber(today)-dayNumber(first)+1):0;const rate=elapsed?total/elapsed:0;return {total,left,month,percent:Math.min(100,total/s.target*100),rate,days:left===0?0:rate>0?Math.ceil(left/rate):null};}
export function milestones(target){let a=[];for(let n=5000000;n<target&&a.length<200;n+=5000000)a.push(n);a.push(target);return a;}
export function buckets(s,period,today=dateKey()){const end=new Date(today+'T12:00:00');let result=[];for(let i=(period==='month'?5:6);i>=0;i--){let start=new Date(end),finish=new Date(end);if(period==='day'){start.setDate(end.getDate()-i);finish=new Date(start)}else if(period==='week'){start.setDate(end.getDate()-((end.getDay()+6)%7)-i*7);finish=new Date(start);finish.setDate(start.getDate()+6)}else{start=new Date(end.getFullYear(),end.getMonth()-i,1,12);finish=new Date(end.getFullYear(),end.getMonth()-i+1,0,12)}let from=dateKey(start),to=dateKey(finish);let ts=s.transactions.filter(t=>t.date>=from&&t.date<=to);const incoming=ts.filter(t=>t.type==='in').reduce((a,t)=>a+t.amount,0),outgoing=ts.filter(t=>t.type==='out').reduce((a,t)=>a+t.amount,0);result.push({from,to,incoming,outgoing,label:start.toLocaleDateString('id-ID',period==='month'?{month:'short'}:{day:'numeric',month:'short'})})}return result;}
